services:
  - type: web
    name: sheeagents
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port= --server.address=0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
